# workflow name
name: Hello world workflow

# events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:

jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello World!"
        shell: bash

  secondJob:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "GoodBye World!"
        shell: bash
