# workflow name
name: second workflow

# events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "Hello World!!!!!"
        shell: bash
